cloud:
  aws:
    s3:
      bucket: yurivongella
    region:
      static: ap-northeast-2
    stack:
      auto: false


spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
      url: jdbc:mysql://localhost:3306/aws_s3?serverTimezone=UTC
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
